# Generated by Django 4.1.7 on 2023-06-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
